In [1]:
#importing imp. lib.
import numpy as np
import pandas as pd

In [2]:
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv("Movie_classification.csv", header = 0)

In [4]:
df.head()

Marketing expense  Production expense  Multiplex coverage     Budget  \
0            20.1264               59.62               0.462  36524.125   
1            20.5462               69.14               0.531  35668.655   
2            20.5458               69.14               0.531  39912.675   
3            20.6474               59.36               0.542  38873.890   
4            21.3810               59.36               0.542  39701.585   

   Movie_length  Lead_ Actor_Rating  Lead_Actress_rating  Director_rating  \
0         138.7               7.825                8.095            7.910   
1         152.4               7.505                7.650            7.440   
2         134.6               7.485                7.570            7.495   
3         119.3               6.895                7.035            6.920   
4         127.7               6.920                7.070            6.815   

   Producer_rating  Critic_rating  Trailer_views 3D_available  Time_taken  \
0            7.995           7.94         527367          YES      109.60   
1            7.470           7.44         494055           NO      146.64   
2            7.515           7.44         547051           NO      147.88   
3            7.020           8.26         516279          YES      185.36   
4            7.070           8.26         531448           NO      176.48   

   Twitter_hastags     Genre  Avg_age_actors  Num_multiplex  Collection  \
0          223.840  Thriller              23            494       48000   
1          243.456     Drama              42            462       43200   
2         2022.400    Comedy              38            458       69400   
3          225.344     Drama              45            472       66800   
4          225.792     Drama              55            395       72400   

   Start_Tech_Oscar  
0                 1  
1                 0  
2                 1  
3                 1  
4                 1

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 19 columns):
Marketing expense      506 non-null float64
Production expense     506 non-null float64
Multiplex coverage     506 non-null float64
Budget                 506 non-null float64
Movie_length           506 non-null float64
Lead_ Actor_Rating     506 non-null float64
Lead_Actress_rating    506 non-null float64
Director_rating        506 non-null float64
Producer_rating        506 non-null float64
Critic_rating          506 non-null float64
Trailer_views          506 non-null int64
3D_available           506 non-null object
Time_taken             494 non-null float64
Twitter_hastags        506 non-null float64
Genre                  506 non-null object
Avg_age_actors         506 non-null int64
Num_multiplex          506 non-null int64
Collection             506 non-null int64
Start_Tech_Oscar       506 non-null int64
dtypes: float64(12), int64(5), object(2)
memory usage: 75.2+ KB


In [6]:
#dealing with missing values

In [7]:
df['Time_taken'].mean()

157.39149797570855

In [11]:
df['Time_taken'].fillna(value =df['Time_taken'].mean() , inplace =True)

In [12]:
df.head()

Marketing expense  Production expense  Multiplex coverage     Budget  \
0            20.1264               59.62               0.462  36524.125   
1            20.5462               69.14               0.531  35668.655   
2            20.5458               69.14               0.531  39912.675   
3            20.6474               59.36               0.542  38873.890   
4            21.3810               59.36               0.542  39701.585   

   Movie_length  Lead_ Actor_Rating  Lead_Actress_rating  Director_rating  \
0         138.7               7.825                8.095            7.910   
1         152.4               7.505                7.650            7.440   
2         134.6               7.485                7.570            7.495   
3         119.3               6.895                7.035            6.920   
4         127.7               6.920                7.070            6.815   

   Producer_rating  Critic_rating  Trailer_views 3D_available  Time_taken  \
0            7.995           7.94         527367          YES      109.60   
1            7.470           7.44         494055           NO      146.64   
2            7.515           7.44         547051           NO      147.88   
3            7.020           8.26         516279          YES      185.36   
4            7.070           8.26         531448           NO      176.48   

   Twitter_hastags     Genre  Avg_age_actors  Num_multiplex  Collection  \
0          223.840  Thriller              23            494       48000   
1          243.456     Drama              42            462       43200   
2         2022.400    Comedy              38            458       69400   
3          225.344     Drama              45            472       66800   
4          225.792     Drama              55            395       72400   

   Start_Tech_Oscar  
0                 1  
1                 0  
2                 1  
3                 1  
4                 1

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 19 columns):
Marketing expense      506 non-null float64
Production expense     506 non-null float64
Multiplex coverage     506 non-null float64
Budget                 506 non-null float64
Movie_length           506 non-null float64
Lead_ Actor_Rating     506 non-null float64
Lead_Actress_rating    506 non-null float64
Director_rating        506 non-null float64
Producer_rating        506 non-null float64
Critic_rating          506 non-null float64
Trailer_views          506 non-null int64
3D_available           506 non-null object
Time_taken             506 non-null float64
Twitter_hastags        506 non-null float64
Genre                  506 non-null object
Avg_age_actors         506 non-null int64
Num_multiplex          506 non-null int64
Collection             506 non-null int64
Start_Tech_Oscar       506 non-null int64
dtypes: float64(12), int64(5), object(2)
memory usage: 75.2+ KB


In [13]:
# Creating dummy variable

In [14]:
df.head()

Marketing expense  Production expense  Multiplex coverage     Budget  \
0            20.1264               59.62               0.462  36524.125   
1            20.5462               69.14               0.531  35668.655   
2            20.5458               69.14               0.531  39912.675   
3            20.6474               59.36               0.542  38873.890   
4            21.3810               59.36               0.542  39701.585   

   Movie_length  Lead_ Actor_Rating  Lead_Actress_rating  Director_rating  \
0         138.7               7.825                8.095            7.910   
1         152.4               7.505                7.650            7.440   
2         134.6               7.485                7.570            7.495   
3         119.3               6.895                7.035            6.920   
4         127.7               6.920                7.070            6.815   

   Producer_rating  Critic_rating  Trailer_views 3D_available  Time_taken  \
0            7.995           7.94         527367          YES      109.60   
1            7.470           7.44         494055           NO      146.64   
2            7.515           7.44         547051           NO      147.88   
3            7.020           8.26         516279          YES      185.36   
4            7.070           8.26         531448           NO      176.48   

   Twitter_hastags     Genre  Avg_age_actors  Num_multiplex  Collection  \
0          223.840  Thriller              23            494       48000   
1          243.456     Drama              42            462       43200   
2         2022.400    Comedy              38            458       69400   
3          225.344     Drama              45            472       66800   
4          225.792     Drama              55            395       72400   

   Start_Tech_Oscar  
0                 1  
1                 0  
2                 1  
3                 1  
4                 1

In [16]:
df = pd.get_dummies(df,columns = ["3D_available","Genre"], drop_first = True)

In [17]:
df.head()

Marketing expense  Production expense  Multiplex coverage     Budget  \
0            20.1264               59.62               0.462  36524.125   
1            20.5462               69.14               0.531  35668.655   
2            20.5458               69.14               0.531  39912.675   
3            20.6474               59.36               0.542  38873.890   
4            21.3810               59.36               0.542  39701.585   

   Movie_length  Lead_ Actor_Rating  Lead_Actress_rating  Director_rating  \
0         138.7               7.825                8.095            7.910   
1         152.4               7.505                7.650            7.440   
2         134.6               7.485                7.570            7.495   
3         119.3               6.895                7.035            6.920   
4         127.7               6.920                7.070            6.815   

   Producer_rating  Critic_rating  ...  Time_taken  Twitter_hastags  \
0            7.995           7.94  ...      109.60          223.840   
1            7.470           7.44  ...      146.64          243.456   
2            7.515           7.44  ...      147.88         2022.400   
3            7.020           8.26  ...      185.36          225.344   
4            7.070           8.26  ...      176.48          225.792   

   Avg_age_actors  Num_multiplex  Collection  Start_Tech_Oscar  \
0              23            494       48000                 1   
1              42            462       43200                 0   
2              38            458       69400                 1   
3              45            472       66800                 1   
4              55            395       72400                 1   

   3D_available_YES  Genre_Comedy  Genre_Drama  Genre_Thriller  
0                 1             0            0               1  
1                 0             0            1               0  
2                 0             1            0               0  
3                 1             0            1               0  
4                 0             0            1               0  

[5 rows x 21 columns]

In [18]:
#X-y split

In [20]:
X = df.loc[:,df.columns!="Start_Tech_Oscar"]

In [22]:
type(X)

pandas.core.frame.DataFrame

In [23]:
X.shape

(506, 20)

In [24]:
y = df["Start_Tech_Oscar"]

In [25]:
type(y)

pandas.core.series.Series

In [28]:
# TRAIN_TEST_SPLIT

In [29]:
from sklearn.model_selection import train_test_split

In [30]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [31]:
X_train.head()

Marketing expense  Production expense  Multiplex coverage     Budget  \
5              20.5970               59.36               0.542  35718.650   
116            22.6316               75.02               0.453  34307.680   
45             23.4284               68.82               0.552  31563.510   
16             41.0786               71.28               0.462  32968.925   
468           331.5140               91.20               0.420  32918.930   

     Movie_length  Lead_ Actor_Rating  Lead_Actress_rating  Director_rating  \
5           132.2               6.890                7.100            6.885   
116         146.0               8.535                8.645            8.500   
45          107.3               7.385                7.525            7.395   
16          102.8               7.670                7.805            7.740   
468         144.5               8.520                8.550            8.440   

     Producer_rating  Critic_rating  Trailer_views  Time_taken  \
5              7.005           7.26         498425      143.48   
116            8.860           8.44         432696      130.48   
45             7.490           8.42         470466      161.72   
16             7.785           7.80         532331      109.24   
468            8.670           6.96         383739      117.64   

     Twitter_hastags  Avg_age_actors  Num_multiplex  Collection  \
5            284.592              53            460       57400   
116          263.392              23            528       42400   
45           223.088              21            445       38600   
16           203.696              46            547       46200   
468          303.056              28            494       38200   

     3D_available_YES  Genre_Comedy  Genre_Drama  Genre_Thriller  
5                   1             1            0               0  
116                 0             1            0               0  
45                  0             0            0               1  
16                  0             1            0               0  
468                 0             1            0               0

In [32]:
X_train.shape

(354, 20)

In [33]:
X_test.shape

(152, 20)

In [34]:
# Standardise data

In [36]:
from sklearn.preprocessing import StandardScaler

In [37]:
sc = StandardScaler().fit(X_train)

In [38]:
X_train_std = sc.transform(X_train)

In [39]:
X_test_std = sc.transform(X_test)

In [40]:
X_test_std

array([[-0.406801  , -1.02225586,  0.40521827, ...,  1.48935618,
        -0.49646639, -0.76181175],
       [-0.41105674, -0.68165068,  0.94540271, ..., -0.67143106,
        -0.49646639,  1.31266025],
       [-0.4051199 ,  2.39678516, -0.44364301, ...,  1.48935618,
        -0.49646639, -0.76181175],
       ...,
       [-0.35439903, -0.71195877,  0.4566644 , ..., -0.67143106,
        -0.49646639,  1.31266025],
       [ 0.25423453,  1.00549958, -1.33537606, ..., -0.67143106,
        -0.49646639, -0.76181175],
       [ 0.77732457,  1.00549958, -1.56688368, ...,  1.48935618,
        -0.49646639, -0.76181175]])

In [41]:
# TRAIN SVM CLASSIFICATION MODEL

In [42]:
from sklearn import svm

In [43]:
clf_svm_1 = svm.SVC(kernel = 'linear', C = 0.01)

In [44]:
clf_svm_1.fit(X_train_std,y_train)

SVC(C=0.01, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='linear', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [45]:
# PREDICTIONS

In [46]:
y_train_pred = clf_svm_1.predict(X_train_std)

In [47]:
y_test_pred = clf_svm_1.predict(X_test_std)

In [48]:
y_test_pred

array([1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1],
      dtype=int64)

In [49]:
# Model Performance

In [50]:
from sklearn.metrics import accuracy_score , confusion_matrix

In [51]:
confusion_matrix(y_test,y_test_pred)

array([[11, 54],
       [13, 74]], dtype=int64)

In [52]:
accuracy_score(y_test,y_test_pred)

0.5592105263157895

In [53]:
clf_svm_1.n_support_

array([164, 166])

In [54]:
# Grid Search

In [55]:
from sklearn.model_selection import GridSearchCV

In [58]:
params = {'C':(0.001,0.005,0.1,0.05,0.1,0.5,1,5,10,50,100,500,1000)}

In [59]:
clf_svm_1 = svm.SVC(kernel='linear')

In [61]:
svm_grid_lin = GridSearchCV(clf_svm_1, params, n_jobs= -1, cv = 10, verbose=1, scoring='accuracy')

In [62]:
svm_grid_lin.fit(X_train_std, y_train)

Fitting 10 folds for each of 13 candidates, totalling 130 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done  34 tasks      | elapsed:    4.1s
[Parallel(n_jobs=-1)]: Done 115 out of 130 | elapsed:   29.5s remaining:    3.8s
[Parallel(n_jobs=-1)]: Done 130 out of 130 | elapsed:  1.0min finished
C:\Users\Yash Srivastava\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:814: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


GridSearchCV(cv=10, error_score='raise-deprecating',
             estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='auto_deprecated', kernel='linear',
                           max_iter=-1, probability=False, random_state=None,
                           shrinking=True, tol=0.001, verbose=False),
             iid='warn', n_jobs=-1,
             param_grid={'C': (0.001, 0.005, 0.1, 0.05, 0.1, 0.5, 1, 5, 10, 50,
                               100, 500, 1000)},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring='accuracy', verbose=1)

In [63]:
svm_grid_lin.best_params_

{'C': 100}

In [64]:
linsvm_clf = svm_grid_lin.best_estimator_

In [69]:
accuracy_score(y_test, linsvm_clf.predict(X_test_std))

0.6842105263157895